# Shapes and slicing nD arrays

In [1]:
import numpy as np

In [2]:
n_rows = 4
n_cols = 5

In [4]:
a = np.arange(n_rows * n_cols)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
b=a.reshape(n_rows, n_cols)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Slicing

In [9]:
b[:, 0] # first column

array([ 0,  5, 10, 15])

In [10]:
b[0,:] # first row

array([0, 1, 2, 3, 4])

In [11]:
b[0:2, 0:3] #print first two rows and first three columns

array([[0, 1, 2],
       [5, 6, 7]])

In [12]:
b[:,1:3] #print all rows and columns 1 and 2

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

## 3D Arrays

In [13]:
nx = 4
ny = 3
nz = 2

In [15]:
d = np.arange(nx * ny * nz)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
e= d.reshape(nz, ny, nx)

In [22]:
e[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])